### CREATE SIMPLE ORDER
POST http://localhost:8080/api/orders/simple
Content-Type: application/json

{
  "orderId": "ORD-001",
  "customerId": "CUST-123",
  "amount": 19.99,
  "status": "PENDING",
  "orderDateTime": "2025-12-06T15:15:15"
}

### GET Current Health
GET http://localhost:8080/actuator/health
Content-Type: application/json
